"""Fixed subclass bug

Revision ID: 4a539d8108fc
Revises: 8c1c9997e122
Create Date: 2026-01-27 00:32:11.528370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a539d8108fc'
down_revision: Union[str, Sequence[str], None] = '8c1c9997e122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'subclass',
               existing_type=postgresql.ENUM('mundano', 'combatente', 'especialista', 'ocultista', 'transformado', name='classes'),
               type_=sa.Enum('combatente', 'especialista', 'ocultista', 'transformado', 'none', name='subclasses'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'subclass',
               existing_type=sa.Enum('combatente', 'especialista', 'ocultista', 'transformado', 'none', name='subclasses'),
               type_=postgresql.ENUM('mundano', 'combatente', 'especialista', 'ocultista', 'transformado', name='classes'),
               existing_nullable=False)
    # ### end Alembic commands ###
