"""Adding Correctly roles in users table

Revision ID: 57b9fe958b88
Revises: b3d0ce5888c8
Create Date: 2026-01-21 20:18:11.480113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '57b9fe958b88'
down_revision: Union[str, Sequence[str], None] = 'b3d0ce5888c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userroles = postgresql.ENUM('master', 'player', name='userroles')
    userroles.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('master', 'player', name='userroles'), nullable=False, server_default='player'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
