"""New initial migration

Revision ID: 8c1c9997e122
Revises: 
Create Date: 2026-01-27 00:28:29.717968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1c9997e122'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('character_class', sa.Enum('mundano', 'combatente', 'especialista', 'ocultista', 'transformado', name='classes'), nullable=False))
    op.add_column('characters', sa.Column('subclass', sa.Enum('combatente', 'especialista', 'ocultista', 'transformado', 'none', name='classes'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'subclass')
    op.drop_column('characters', 'character_class')
    # ### end Alembic commands ###
