"""modifying character table

Revision ID: 9ac476c93308
Revises: 93a7d53898d2
Create Date: 2026-01-22 22:34:36.960779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ac476c93308'
down_revision: Union[str, Sequence[str], None] = '93a7d53898d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('nex_total', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('nex_class', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('nex_subclass', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('healthy_points', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('atrib_agility', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('atrib_intellect', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('atrib_vitallity', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('atrib_presence', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('atrib_strength', sa.Integer(), nullable=False))
    op.alter_column('characters', 'origin',
               existing_type=postgresql.ENUM('academico', 'agente_de_saude', 'amnesico', name='charactersorigins'),
               type_=sa.Enum('academico', 'agente_de_saude', 'amnesico', 'artista', 'atleta', 'chef', 'cientista_forense', 'criminoso', 'cultista_arrependido', 'desgarrado', 'engenheiro', 'executivo', 'escritor', 'investigador', 'jornalista', 'lutador', 'magnata', 'mercenario', 'militar', 'operario', 'policial', 'professor', 'religioso', 'servidor_publico', 'teorico_da_conspiracao', 'ti', 'trabalhador_rural', 'trambiqueiro', 'universitario', 'vitima', 'prodigio_paranormal', 'oficial_militar', name='origins', native_enum=False),
               existing_nullable=False)
    op.alter_column('characters', 'character_class',
               existing_type=postgresql.ENUM('mundano', 'combatente', 'especialista', 'ocultista', name='charactersclasses'),
               type_=sa.Enum('mundano', 'combatente', 'especialista', 'ocultista', 'transformado', name='classes', native_enum=False),
               existing_nullable=False)
    op.alter_column('characters', 'rank',
               existing_type=postgresql.ENUM('none', 'recruta', 'operador', 'agente_especial', 'oficial_de_operacoes', 'agente_de_elite', name='charactersRanks'),
               type_=sa.Enum('none', 'recruta', 'operador', 'agente_especial', 'oficial_de_operacoes', 'agente_de_elite', name='ranks', native_enum=False),
               existing_nullable=False)
    op.drop_column('characters', 'nex')
    op.drop_column('characters', 'healty_points')
    op.drop_column('characters', 'trail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('trail', postgresql.ENUM('none', 'aniquilador', 'comandante_de_campo', 'guerreiro', 'operacoes_especiais', 'tropa_de_choque', 'atirador_de_elite', 'infiltrador', name='characterstrails'), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('healty_points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('nex', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('characters', 'rank',
               existing_type=sa.Enum('none', 'recruta', 'operador', 'agente_especial', 'oficial_de_operacoes', 'agente_de_elite', name='ranks', native_enum=False),
               type_=postgresql.ENUM('none', 'recruta', 'operador', 'agente_especial', 'oficial_de_operacoes', 'agente_de_elite', name='charactersRanks'),
               existing_nullable=False)
    op.alter_column('characters', 'character_class',
               existing_type=sa.Enum('mundano', 'combatente', 'especialista', 'ocultista', 'transformado', name='classes', native_enum=False),
               type_=postgresql.ENUM('mundano', 'combatente', 'especialista', 'ocultista', name='charactersclasses'),
               existing_nullable=False)
    op.alter_column('characters', 'origin',
               existing_type=sa.Enum('academico', 'agente_de_saude', 'amnesico', 'artista', 'atleta', 'chef', 'cientista_forense', 'criminoso', 'cultista_arrependido', 'desgarrado', 'engenheiro', 'executivo', 'escritor', 'investigador', 'jornalista', 'lutador', 'magnata', 'mercenario', 'militar', 'operario', 'policial', 'professor', 'religioso', 'servidor_publico', 'teorico_da_conspiracao', 'ti', 'trabalhador_rural', 'trambiqueiro', 'universitario', 'vitima', 'prodigio_paranormal', 'oficial_militar', name='origins', native_enum=False),
               type_=postgresql.ENUM('academico', 'agente_de_saude', 'amnesico', name='charactersorigins'),
               existing_nullable=False)
    op.drop_column('characters', 'atrib_strength')
    op.drop_column('characters', 'atrib_presence')
    op.drop_column('characters', 'atrib_vitallity')
    op.drop_column('characters', 'atrib_intellect')
    op.drop_column('characters', 'atrib_agility')
    op.drop_column('characters', 'healthy_points')
    op.drop_column('characters', 'nex_subclass')
    op.drop_column('characters', 'nex_class')
    op.drop_column('characters', 'nex_total')
    # ### end Alembic commands ###
