"""create charactes table

Revision ID: cfb0711103cf
Revises: 57b9fe958b88
Create Date: 2026-01-22 00:26:55.894091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb0711103cf'
down_revision: Union[str, Sequence[str], None] = '57b9fe958b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('nex', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('academico', 'agente_de_saude', 'amnesico', name='charactersorigins'), nullable=False),
    sa.Column('character_class', sa.Enum('mundano', 'combatente', 'especialista', 'ocultista', name='charactersclasses'), nullable=False),
    sa.Column('trail', sa.Enum('none', 'aniquilador', 'comandante_de_campo', 'guerreiro', 'operacoes_especiais', 'tropa_de_choque', 'atirador_de_elite', 'infiltrador', name='characterstrails'), nullable=False),
    sa.Column('rank', sa.Enum('none', 'recruta', 'operador', 'agente_especial', 'oficial_de_operacoes', 'agente_de_elite', name='charactersRanks'), nullable=False),
    sa.Column('healty_points', sa.Integer(), nullable=False),
    sa.Column('sanity_points', sa.Integer(), nullable=False),
    sa.Column('effort_points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
